{% set version = "1.2.1" %}

package:
  name: dolfyn
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/d/dolfyn/dolfyn-{{ version }}.tar.gz
  sha256: c62646124ea0d71917442df9d87f1ccc5c6d6db51300a4d2144b3261bee8a18f

build:
  number: 0
  # cannot be noarch b/c of scripts
  # noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - numpy >=1.21
    - scipy >=1.7.0
    - xarray >=0.18.2
    - netcdf4 >=1.5.7
    - bottleneck

test:
  imports:
    - dolfyn
    - dolfyn.adp
    - dolfyn.adv
    - dolfyn.io
    - dolfyn.tools
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/lkilcher/dolfyn
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Doppler Ocean Library for pYthoN

extra:
  recipe-maintainers:
    - ocefpaf
