{% set version = "1.0.0" %}

package:
  name: dolfyn
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/d/dolfyn/dolfyn-{{ version }}.tar.gz
  sha256: 3fcbc9d5735620337b41dd4d901411c31eca6bcbf4d7e62850888bc47f549e86

build:
  number: 0
  # cannot be noarch b/c of scripts
  # noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - netcdf4 >=1.5.7
    - numpy >=1.21
    - scipy >=1.7.0
    - xarray >=0.18.2

test:
  imports:
    - dolfyn
    - dolfyn.adp
    - dolfyn.adv
    - dolfyn.io
    - dolfyn.tools
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/lkilcher/dolfyn
  license: Apache-2.0
  license_file: LICENSE.txt
  summary: Doppler Ocean Library for pYthoN

extra:
  recipe-maintainers:
    - ocefpaf
