{% set version = "0.13.0" %}

package:
  name: dolfyn
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/d/dolfyn/dolfyn-{{ version }}.tar.gz
  sha256: 01c2a66170a79fa1413d7792e2e9ace742680d3c21e7566fbf0697a41be2de58

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - netcdf4
    - numpy
    - scipy
    - six
    - xarray

test:
  imports:
    - dolfyn
    - dolfyn.adp
    - dolfyn.adv
    - dolfyn.io
    - dolfyn.tools
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/lkilcher/dolfyn
  license: Apache-2.0
  license_file: LICENSE.txt
  summary: Doppler Ocean Library for pYthoN

extra:
  recipe-maintainers:
    - ocefpaf
