{% set version = "1.3.0" %}

package:
  name: dolfyn
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/d/dolfyn/dolfyn-{{ version }}.tar.gz
  sha256: e79948b8d156c3ad39d091480b05b4ed9f117399e4b3213c09f9b99a69d2e379

build:
  number: 1
  # cannot be noarch b/c of scripts
  # noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - numpy >=1.21
    - scipy >=1.7.0
    - xarray >=0.18.2
    - netcdf4 >=1.5.7
    - bottleneck

test:
  imports:
    - dolfyn
    - dolfyn.adp
    - dolfyn.adv
    - dolfyn.io
    - dolfyn.tools
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/lkilcher/dolfyn
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Doppler Ocean Library for pYthoN

extra:
  recipe-maintainers:
    - ocefpaf
