{% set version = "0.12.1" %}

package:
  name: dolfyn
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/d/dolfyn/dolfyn-{{ version }}.tar.gz
  sha256: 9a6d41d29486dc06df7242acabb0ff7764dde01be2c0c7e5194368cde100d991

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - setuptools
    - h5py
    - numpy
    - pydicth5
    - scipy

test:
  imports:
    - dolfyn
    - dolfyn.adp
    - dolfyn.adv
    - dolfyn.data
    - dolfyn.io
    - dolfyn.meta
    - dolfyn.tools
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/lkilcher/dolfyn
  license: Apache-2.0
  license_file: LICENSE.txt
  summary: Doppler Ocean Library for pYthoN

extra:
  recipe-maintainers:
    - ocefpaf
