travis:
  secure:
    BINSTAR_TOKEN: NymbOhmc6OeUmBZ0rGKdJxRaHyXV/jud4zZ53Z5SiU4uRXk5QI2FkYfs8pMiApLFUkmirRlNLsLWOxMJO6SyLdxJpY7tDZTh8wBUxlwH5F7JICFubjB7cmYS60UN5PzLJ3VjXEaiMLm7d/NbjjgkxBJ8v4s0fk6M+UGQfmmYDpPVSCZREQBgGsguRFDzRm9Mg0HO+lkeEsZagCXGztdb1GoKeYDTBEJ+R7mKjb+N/hPYkrE4ELYg924h8Kd2k350lWLMIHVhRr1GpH4/RoMtMCdGQYUrD4Qt37GcF5mkJAXwnYkgcU5/PsGQotPfKwS/HKwMEaf4zpx8m1zsIKUvDoDZxjipyxhYhBro11IZp4Att1D344ArSyhFBD586zJW4JPfOyVdH9eIVpupvxCaanJf5We6PPVX5eNk9KBIjwqEQ3i/70gemRuyd4p0SoQfkypk9N/WPGS0sHgu3VN4nx7WvLF/VSW6bFzYFmeuBG9ffNZ3Arbyk9lQzTeLLCbfDdt5n6Aes8XFGkSTVQwGJM4cmcApujPjLC0K88Xj+mnO/0qTXTRE+ih/32MXIAsjtGUIZbnFAhf/B72Rx8g7pKwZUA1BIi4wg5MF7h3mw1LX9hptzU5aPm4lReat0rD2jVqRqatDsX+kCXFaEFVxBlet7FJpzRO/8S5FLYFrJLE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
